# Generated by Django 3.2.7 on 2021-10-15 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tipodocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('documento', models.IntegerField()),
                ('fechadenacimiento', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=15)),
                ('confirmarcontraseña', models.CharField(max_length=15)),
                ('lugardenacimiento', models.CharField(max_length=50)),
                ('idlugarresiedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistroUsuarios.ciudad')),
                ('idtipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistroUsuarios.tipodocumento')),
            ],
        ),
    ]
